// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Category = "Video" | "Audio" | "Archives" | "Documents" | "Images" | "Programs" | "Other";
