// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { JobSpec } from "./JobSpec";
import type { Priority } from "./Priority";
import type { RequestEnvelope } from "./RequestEnvelope";
import type { Resolution } from "./Resolution";
import type { Settings } from "./Settings";
import type { SubscriptionScope } from "./SubscriptionScope";

export type Command = { "cmd": "hello", client: string, protocol: number, } | { "cmd": "submit", spec: JobSpec, } | { "cmd": "pause", job: JobId, } | { "cmd": "resume", job: JobId, } | { "cmd": "cancel", job: JobId, } | { "cmd": "remove", job: JobId, deleteFile: boolean, } | { "cmd": "reprioritize", job: JobId, priority: Priority, } | { "cmd": "decide", job: JobId, resolution: Resolution, } | { "cmd": "retryMux", job: JobId, } | { "cmd": "probe", envelope: RequestEnvelope, } | { "cmd": "probeMedia", envelope: RequestEnvelope, } | { "cmd": "subscribe", scope: SubscriptionScope, } | { "cmd": "list" } | { "cmd": "clearCompleted" } | { "cmd": "getSettings" } | { "cmd": "setSettings", settings: Settings, } | { "cmd": "renewedUrl", job: JobId, envelope: RequestEnvelope, } | { "cmd": "ping" };
