// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A question only the user can answer. Every variant leaves the job fully resumable.
 */
export type Decision = { "kind": "fileChanged", detail: string, } | { "kind": "diskFull", needed: number, drive: string, } | { "kind": "nameConflict", path: string, } | { "kind": "permissionDenied", path: string, } | { "kind": "urlUnrecoverable", pageUrl?: string | null, } | { "kind": "integrityMismatch", detail: string, } | { "kind": "muxFailed", detail: string, };
