// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { JobState } from "./JobState";
import type { JobView } from "./JobView";
import type { MediaCandidate } from "./MediaCandidate";
import type { Outcome } from "./Outcome";
import type { ProbeResult } from "./ProbeResult";
import type { ProgressFrame } from "./ProgressFrame";
import type { RenewalHint } from "./RenewalHint";
import type { Settings } from "./Settings";
import type { SummaryFrame } from "./SummaryFrame";
import type { TabId } from "./TabId";

export type Event = { "event": "hello", daemon: string, protocol: number, } | { "event": "pong" } | { "event": "jobAdded", job: JobView, } | { "event": "jobProgress", job: JobId, frame: ProgressFrame, } | { "event": "jobSummary", job: JobId, frame: SummaryFrame, } | { "event": "jobStateChanged", job: JobId, state: JobState, } | { "event": "jobFinished", job: JobId, outcome: Outcome, } | { "event": "jobRemoved", job: JobId, } | { "event": "urlExpired", job: JobId, hint: RenewalHint, } | { "event": "mediaFound", tab: TabId, candidates: Array<MediaCandidate>, } | { "event": "probed", result: ProbeResult, } | { "event": "settingsChanged", settings: Settings, } | { "event": "jobs", jobs: Array<JobView>, } | { "event": "error", message: string, };
