// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Monotonic, assigned by the daemon, stable across restarts.
 */
export type JobId = number;
