// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";

/**
 * The vocabulary the UI signposts with. An action keeps its name through the whole flow
 * (05 §Copy), so these are user-visible states, not internal jargon.
 */
export type JobState = { "kind": "queued" } | { "kind": "probing" } | { "kind": "downloading" } | { "kind": "stalled", reason: string, } | { "kind": "muxing" } | { "kind": "paused" } | { "kind": "needsDecision", decision: Decision, } | { "kind": "completed" } | { "kind": "failed", error: string, };
