// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { MediaSelection } from "./MediaSelection";
import type { Priority } from "./Priority";
import type { RequestEnvelope } from "./RequestEnvelope";

export type JobSpec = { envelope: RequestEnvelope, 
/**
 * Absolute destination directory. `None` = the configured default for the category.
 */
destDir?: string | null, 
/**
 * Explicit filename, already chosen by the user. `None` = derive it (04 §8).
 */
filename?: string | null, category?: Category | null, priority: Priority, startPaused: boolean, 
/**
 * Present when this job assembles a stream rather than fetching one file.
 */
media?: MediaSelection | null, };
