// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { JobId } from "./JobId";
import type { JobState } from "./JobState";
import type { MediaSummary } from "./MediaSummary";
import type { Priority } from "./Priority";
import type { Protocol } from "./Protocol";
import type { Retries } from "./Retries";
import type { TransferMode } from "./TransferMode";
import type { Verification } from "./Verification";

/**
 * The full record of a job. Sent on `JobAdded` and on any structural change.
 */
export type JobView = { id: JobId, filename: string, destPath: string, url: string, host: string, category: Category, state: JobState, priority: Priority, total?: number | null, completed: number, mode: TransferMode, protocol?: Protocol | null, 
/**
 * Distinct resolved addresses in use — "4 addresses · releases.ubuntu.com".
 */
addresses: number, createdAt: number, finishedAt?: number | null, 
/**
 * `Some` once a server-offered checksum has been checked (02 §7).
 */
verified?: Verification | null, retries: Retries, media?: MediaSummary | null, };
