// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerPreference } from "./ContainerPreference";
import type { MediaKind } from "./MediaKind";

/**
 * What the overlay's Download button submits.
 */
export type MediaSelection = { manifestUrl: string, kind: MediaKind, title: string, variantId: string, audioId?: string | null, subtitleIds: Array<string>, container: ContainerPreference, };
