// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";
import type { MediaTrack } from "./MediaTrack";
import type { MediaVariant } from "./MediaVariant";

export type MediaCandidate = { 
/**
 * Stable id for this manifest within the tab.
 */
id: string, manifestUrl: string, kind: MediaKind, title: string, durationSecs?: number | null, live: boolean, variants: Array<MediaVariant>, audio: Array<MediaTrack>, subtitles: Array<MediaTrack>, 
/**
 * Index into `variants` nearest the resolution actually playing (04 §3).
 */
defaultVariant?: number | null, };
