// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaVariant = { id: string, width?: number | null, height?: number | null, bandwidth: number, codecLabel?: string | null, 
/**
 * `bandwidth × duration / 8`. A peak declaration — the UI marks it `~` (04 §1-2).
 */
estimatedBytes?: number | null, audioGroup?: string | null, };
