// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaTrack = { id: string, label: string, language?: string | null, codecLabel?: string | null, estimatedBytes?: number | null, default: boolean, };
