// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live media detail for the row: which phase, and how many segments are missing.
 */
export type MediaSummary = { segmentsTotal: number, segmentsDone: number, segmentsMissing: number, muxPercent?: number | null, 
/**
 * e.g. "Saved as MKV — MP4 can't hold Opus audio."
 */
containerNote?: string | null, };
