// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verification } from "./Verification";

export type Outcome = { "kind": "completed", path: string, bytes: number, elapsedSecs: number, verified?: Verification | null, } | { "kind": "cancelled" } | { "kind": "failed", error: string, };
