// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { TransferMode } from "./TransferMode";

/**
 * What the New Download sheet renders before the user commits (05 §Screens).
 */
export type ProbeResult = { url: string, finalUrl: string, filename: string, host: string, size?: number | null, mimeType?: string | null, mode: TransferMode, resumable: boolean, category: Category, suggestedDir?: string | null, };
