// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerFrame } from "./WorkerFrame";

/**
 * 20 Hz, `Detail` subscribers only. Roughly 300 bytes thanks to the RLE runs.
 */
export type ProgressFrame = { total?: number | null, completed: number, 
/**
 * EWMA, 3 s half-life — smoothed before it is ever displayed.
 */
bps: number, etaSecs?: number | null, connections: number, blockSize: number, blocks: number, 
/**
 * Run-length encoded block bitmap: `(start_block, len, owner)`.
 * `owner` 0 = complete, 1..=N = in flight by worker N.
 */
runs: Array<[number, number, number]>, 
/**
 * Per-worker readout for the expanded row (05 §Segment map).
 */
workers: Array<WorkerFrame>, };
