// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabId } from "./TabId";

export type RenewalHint = { url: string, pageUrl?: string | null, tabId?: TabId | null, 
/**
 * Why the URL is considered dead. For logs, not for the user.
 */
reason: string, };
