// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabId } from "./TabId";

/**
 * Everything the browser sent, captured verbatim. Replaying this exactly is what makes
 * handoff work; divergence is the number one cause of a 403 after takeover.
 */
export type RequestEnvelope = { url: string, 
/**
 * Post-redirect URL, when the browser already knows it.
 */
finalUrl?: string | null, method: string, 
/**
 * Ordered and case-preserved, exactly as the browser sent them.
 */
headers: Array<[string, string]>, 
/**
 * Serialized cookie header value, including HttpOnly cookies the page cannot read.
 */
cookies?: string | null, bodyBase64?: string | null, mimeType?: string | null, contentLength?: number | null, filenameHint?: string | null, tabId?: TabId | null, pageUrl?: string | null, pageTitle?: string | null, capturedAt: number, };
