// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's answer to a `Decision`.
 */
export type Resolution = { "kind": "startOver" } | { "kind": "keepBoth" } | { "kind": "retry" } | { "kind": "cancel" } | { "kind": "changeFolder", destDir: string, } | { "kind": "rename", filename: string, };
