// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerPreference } from "./ContainerPreference";
import type { Theme } from "./Theme";

export type Settings = { downloadDir: string, 
/**
 * Per-category subdirectory, relative to `download_dir` unless absolute.
 */
categoryDirs: { [key in string]: string }, 
/**
 * Ceiling, not a target — the controller finds the real number per origin.
 */
maxConnections: number, maxConcurrentJobs: number, 
/**
 * Bytes per second, 0 = unlimited.
 */
globalSpeedLimit: number, enableH3: boolean, enableCapture: boolean, 
/**
 * Origins the user opted out of capture on.
 */
siteOptouts: Array<string>, minCaptureBytes: number, defaultMediaHeight: number, container: ContainerPreference, subtitles: boolean, theme: Theme, reducedMotion: boolean, clipboardMonitor: boolean, autostart: boolean, 
/**
 * Memory ceiling for the writer's reorder window, in bytes.
 */
writeBufferBudget: number, };
