// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";

export type SubscriptionScope = { "kind": "summary" } | { "kind": "detail", job: JobId, } | { "kind": "none" };
