// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 2 Hz, `Summary` subscribers. Everything a collapsed row needs and nothing more.
 */
export type SummaryFrame = { total?: number | null, completed: number, bps: number, etaSecs?: number | null, connections: number, blocks: number, 
/**
 * Coarse map for the 6 px collapsed bar.
 */
runs: Array<[number, number, number]>, };
