// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *The browser's tab id, carried through so the overlay can be addressed.
 */
export type TabId = number;
