// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the engine will move the bytes. Decided by the probe and shown in the New Download
 * sheet before the user commits (05 §Screens).
 */
export type TransferMode = "Parallel" | "Single";
