// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Verification = { 
/**
 * e.g. "SHA-256". Named in the UI on hover; never a fake green tick.
 */
algorithm: string, ok: boolean, };
