// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkerFrame = { 
/**
 * 1-based lane number. The expanded view numbers lanes so color is never the sole
 * carrier of meaning (05 §Quality floor).
 */
lane: number, bps: number, 
/**
 * Recent throughput samples for the sparkline, oldest first.
 */
spark: Array<number>, stealingFrom: boolean, };
